# Generated by Django 3.2.5 on 2021-07-14 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avenger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avengeruser',
            name='address',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='avengeruser',
            name='address1',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='avengeruser',
            name='email',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
    ]
