# Generated by Django 3.2.5 on 2021-07-14 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('avenger', '0002_auto_20210714_0934'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackOrderUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=None, max_length=256, null=True)),
                ('killed_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='black_order_killed_by', to='avenger.avengeruser')),
            ],
        ),
    ]
